apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-2
spec:
  type: NodePort
  selector:
    app: flask-app-2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30303