apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-4
  namespace: myapp-4
spec:
  selector:
    matchLabels:
      app: flask-app-4
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app-4
    spec:
      containers:
      - name: flask-app-4
        image: shafink/dummy-flask-app:v4
        ports:
        - containerPort: 5000
