apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-4
  namespace: myapp-4
spec:
  type: NodePort
  selector:
    app: flask-app-4
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30603