apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app.kubernetes.io/instance: myapp-argo-application
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30403